### ISSUE TITLE
Display wind and windspeed

### ISSUE THREAD

**Issue by iachievedit** [iachievedit/weatherfxlite#3]
A feature request to display wind speed and direction

`"windDirection":136,"windGustSpeedMax":15.91,"windSpeed":7.22,"windSpeedMax":8.26}}]}}`

I am assuming that is km/h and the direction is 0-360.

**Comment by afast** [comment]
why would it be km/h?

**Comment by iachievedit** [comment]
Pushed windspeed update to `develop`.  Also, to @afast question, the Apple Weather API returns metric units.
